blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: discord.gg/whember
    about: Please ask and answer questions here.
  - name: Heroku, Repl.it, Blocked site issues
    url: https://www.youtube.com/@Whember/sub_confirmation=1
    about: Do not create issues for these.
